sudo: false

language: ruby

before_install:
  - gem update --system
  - gem install bundler
  - npm install --global gulp-cli
  - sudo apt-get install -y pandoc

install:
  - bundle install
  - npm install

script:
  - gulp build
  - bundle exec jekyll build
  - sed -i '/\_posts\//d' .gitignore

branches:
  only:
  - release

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target-branch: master
  on:
    branch: release

cache: bundler
